### PR TITLE
fix(skills): use managed integrations root for slash activation

### LINKED ISSUE #4568: [Bug] Slash skill activation crashes due to an uninitialized integrations root attribute
### Before you start

- [x] I searched [existing issues](https://github.com/bytedance/deer-flow/issues?q=is%3Aissue) and this is not a duplicate.
- [x] I can reproduce this on the latest `main`.

### Problem summary

Invoking any installed and enabled slash skill causes the run to fail before model invocation because UserScopedSkillStorage.validate_skill_file_path() references an uninitialized _user_integrations_root attribute.

### Affected area(s)

Backend API (gateway / endpoints / SSE)

### What happened?

After managed integration skills support was introduced in #3971, activating any installed and enabled slash skill causes the run to fail immediately.

For example:

```text
/ppt-generation Create a simple presentation
```

fails with:

```
AttributeError: 'UserScopedSkillStorage' object has no attribute '_user_integrations_root'
```

Image

### Expected behavior

Everything is ok!

### Steps to reproduce

1. Check out the latest `main` containing commit `4582a41347fa5680238e8dd5c8a7d0468ad6c606`.
2. Configure DeerFlow normally.
3. Start the Docker development environment:

   ```bash
   make docker-start
   ```
4. Open http://localhost:2026.

5. Create a new conversation.

6. Send: /ppt-generation Create a simple presentation

7. Observe that the run enters the error state before producing an assistant response.

### Relevant logs

```shell
none
```

### How are you running DeerFlow?

Docker (make docker-start)

### Operating system

macOS

### Platform details

_No response_

### Python version

_No response_

### Node.js version

_No response_

### pnpm version

_No response_

### uv version

_No response_

### Git state

_No response_

### Support bundle summary

Not included. The issue is reproducible on the latest main and is caused by a deterministic source-level attribute mismatch. A redacted support bundle can be provided if additional environment evidence is needed.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Huixin615**
Fixes  #4568

## Why

Activating a slash skill with `UserScopedSkillStorage` failed before the first
model call with:

`AttributeError: 'UserScopedSkillStorage' object has no attribute '_user_integrations_root'`

The storage constructor initializes the global managed integration skill
directory as `_integrations_root`, but the compatibility getter and skill-file
path validation referenced the nonexistent `_user_integrations_root`.

Because all allowed roots were evaluated before validation began, this also
broke public slash skills such as `/ppt-generation`, even though their files
were located under the valid public skills root.

## What changed

- Kept `get_user_integrations_root()` for compatibility, but made it return the
  initialized global `_integrations_root`.
- Updated skill-file validation to allow:
  - global public skills;
  - per-user custom skills;
  - global managed integration skills.
- Kept rejection of files outside all three trusted roots.
- Updated validation errors and storage documentation to describe the three
  allowed roots accurately.
- Corrected the repository documentation:
  - managed integration skill packs are globally installed under
    `{DEER_FLOW_HOME}/integrations/skills/{provider}/`;
  - integration credentials and enabled state remain per-user.
- Added regression coverage for the storage roots and a real
  `UserScopedSkillStorage` slash-activation path.
- Did not widen middleware exception handling or suppress `AttributeError`.

## Surface area

- [ ] **Frontend UI** — page / component / setting / interaction under `frontend/`
- [ ] **Backend API** — endpoint / SSE event / request-response shape under `backend/app`
- [ ] **Agents / LangGraph** — agent node, graph wiring, `langgraph.json`, or prompt change
- [ ] **Sandbox** — `docker/` or sandboxed execution
- [x] **Skills** — change under `skills/`
- [ ] **Dependencies** — new/upgraded entry in `backend/pyproject.toml` or `frontend/package.json` (say what it buys us)
- [ ] **Default behavior change** — changes existing behavior without the user opting in (default model, default setting, data shape)
- [ ] **Docs / tests / CI only** — no runtime behavior change

## Screenshots / Recording

Manual Docker verification passed with `/ppt-generation`: the run entered normal
model processing and completed without the `_user_integrations_root` exception.

image

## Bug fix verification

- Test paths that reproduce the bug:
  - `backend/tests/test_user_scoped_skill_storage.py`
  - `backend/tests/test_slash_skills.py`
- Did they go red on `main` and green on this branch? **Yes**
- Before the fix, all four new regression cases failed with the same
  `_user_integrations_root` `AttributeError`.
- After the fix, all four cases pass, including public slash-skill activation
  through a real `UserScopedSkillStorage` and a stub model handler.

## Validation

- `uv run pytest -q tests/test_user_scoped_skill_storage.py tests/test_slash_skills.py`
  - `70 passed`
- `cd backend && make format`
  - passed
- `cd backend && make lint`
  - passed
- `cd backend && make test`
  - `10202 passed, 61 skipped, 1 failed`
  - The single local failure was unrelated:
    `TestAgentsAPI.test_create_agent_with_model_and_tool_groups` expected the
    locally unconfigured `deepseek-v3` model.
  - Re-running that test without the local `config.yaml` override passed.
- Manual Docker verification:
  - `/ppt-generation` completed successfully;
  - no `_user_integrations_root` exception occurred.
- Frontend E2E was not run because no frontend files changed.

### CODE REVIEW

File: backend/packages/harness/deerflow/skills/storage/user_scoped_skill_storage.py [hunk 1]
```diff
@@ -386,25 +386,34 @@ def get_user_custom_root(self) -> Path:
         return self._user_custom_root
 
     def get_user_integrations_root(self) -> Path:
-        """Host path to this user's managed integration skills root directory."""
-        return self._user_integrations_root
+        """Host path to the global managed integration skills root directory."""
```
Comment (willem-bd) [inline backend/packages/harness/deerflow/skills/storage/user_scoped_skill_storage.py:389]: Minor naming nit: the method is now misleading since it returns the global `_integrations_root` (no `user_id` component in `Paths.integration_skills_dir()`), but the name still says `user_integrations`. A repo-wide search finds no callers outside this module and the new test added in this PR, so the compatibility surface is essentially internal. Consider renaming to `get_integrations_root()` (or adding it as an alias and deprecating this one) so future readers don't assume the path is user-scoped. Happy to leave as-is if you want to keep the name stable for external consumers.

**Review by willem-bd — COMMENTED** [review]
Bug fix looks correct: `get_user_integrations_root()` and `validate_skill_file_path` referenced a non-existent `_user_integrations_root`, and this PR aligns them with the `_integrations_root` already initialized in `__init__`. The AGENTS.md / docstring corrections match the actual `Paths.integration_skills_dir()` layout (global, not per-user), and the new regression tests cover both the storage roots and a real `UserScopedSkillStorage` slash-activation path through the middleware. One small naming nit inline.

**Review by WillemJiang — APPROVED** [review]
