### ISSUE TITLE
[Bug] Slash skill activation crashes due to an uninitialized integrations root attribute

### ISSUE THREAD

**Issue by Huixin615** [bytedance/deer-flow#4568]
### Before you start

- [x] I searched [existing issues](https://github.com/bytedance/deer-flow/issues?q=is%3Aissue) and this is not a duplicate.
- [x] I can reproduce this on the latest `main`.

### Problem summary

Invoking any installed and enabled slash skill causes the run to fail before model invocation because UserScopedSkillStorage.validate_skill_file_path() references an uninitialized _user_integrations_root attribute.

### Affected area(s)

Backend API (gateway / endpoints / SSE)

### What happened?

After managed integration skills support was introduced in #3971, activating any installed and enabled slash skill causes the run to fail immediately.

For example:

```text
/ppt-generation Create a simple presentation
```

fails with:

```
AttributeError: 'UserScopedSkillStorage' object has no attribute '_user_integrations_root'
```

<img width="2412" height="1508" alt="Image" src="https://github.com/user-attachments/assets/40bdd385-de81-4afd-aa2c-577ed4ae0326" />

### Expected behavior

Everything is ok!

### Steps to reproduce

1. Check out the latest `main` containing commit `4582a41347fa5680238e8dd5c8a7d0468ad6c606`.
2. Configure DeerFlow normally.
3. Start the Docker development environment:

   ```bash
   make docker-start
   ```
4. Open http://localhost:2026.

5. Create a new conversation.

6. Send: /ppt-generation Create a simple presentation

7. Observe that the run enters the error state before producing an assistant response.

### Relevant logs

```shell
none
```

### How are you running DeerFlow?

Docker (make docker-start)

### Operating system

macOS

### Support bundle summary

Not included. The issue is reproducible on the latest main and is caused by a deterministic source-level attribute mismatch. A redacted support bundle can be provided if additional environment evidence is needed.

**Comment by Huixin615** [comment]
我来修复一下这个问题
